package com.administracion.constant;

/**
 * Clase constante que contiene los DMLs Y DDLs para las consultas nativas
 */
public class SQLConstant {

	public static final String SELECT_EMPRESAS_BASE = "SELECT e.ID_EMPRESA,e.NIT_EMPRESA,e.RAZON_SOCIAL FROM EMPRESAS e ORDER BY e.RAZON_SOCIAL";
	public static final String SELECT_PRODUCTOS_EMPRESA_BASE = "SELECT p.ID_PRODUCTO, p.NOMBRE FROM EMPRESAS_PRODUCTOS ep INNER JOIN PRODUCTOS p ON p.ID_PRODUCTO=ep.ID_PRODUCTO WHERE ep.ID_EMPRESA=:idEmpresa ORDER BY p.NOMBRE";
	
	public static final String SELECT_EMPRESAS_POR_ID_USAURIO = "SELECT em.id_empresa, em.nit_empresa, em.razon_social, em.direccion, em.telefono, em.representante_legal, em.id_empresa_padre FROM EMPRESAS em  "
			+ " WHERE em.id_empresa IN  (SELECT id_empresa FROM USUARIOS_ROLES_EMPRESAS usurolRmp WHERE usurolRmp.id_usuario = :idUSuario)";
	
	public static final String SELECT_PRODUCTOS_ID_EMPRESA = "SELECT p.ID_PRODUCTO, p.NOMBRE, ep.VALOR_MINIMO, ep.VALOR_MAXIMO, ep.VALOR_MAXIMO_DIA, ep.HORA_INICIO_VENTA, ep.HORA_FINAL_VENTA, ep.ID_EMPRESA  "
			+ " FROM EMPRESAS_PRODUCTOS ep INNER JOIN PRODUCTOS p ON p.ID_PRODUCTO=ep.ID_PRODUCTO WHERE ep.ID_EMPRESA = :idEmpresa AND ep.ID_ESTADO = 'ACTIVO' ORDER BY p.NOMBRE";
	
	public static final String SELECT_EMPRESAS_PRODUCTOS_COMISIONES_ID_EMPRESA = "SELECT epc.ID_EMPRESA, epc.ID_PRODUCTO, epc.ID_COMISION, epc.PORCENTAJE_COMISION, epc.VALOR_FIJO_COMISION, epc.ID_EMP_PRO_COM, p.NOMBRE "
			+ " FROM EMPRESAS_PRODUCTOS_COMISIONES epc INNER JOIN EMPRESAS em ON em.ID_EMPRESA = epc.ID_EMPRESA INNER JOIN PRODUCTOS p on p.ID_PRODUCTO = epc.ID_PRODUCTO WHERE em.ID_EMPRESA = :idEmpresa AND p.ID_PRODUCTO = :idProducto AND epc.id_estado = 'ACTIVO' ORDER BY p.NOMBRE";
	
	public static final String SELECT_CUENTAS_PRODUCTOS_EMPRESA = "SELECT cp.ID_EMPRESA, cp.ID_PRODUCTO, cp.ID_CUENTA, cp.COD_CUENTA, c.NOMBRE, cp.CUENTA_ASOCIADA, p.NOMBRE AS nombre_producto "
			+ " FROM CUENTAS_PRODUCTOS cp INNER JOIN EMPRESAS em ON em.ID_EMPRESA = cp.ID_EMPRESA INNER JOIN PRODUCTOS p on p.ID_PRODUCTO = cp.ID_PRODUCTO INNER JOIN CUENTAS c on c.ID_CUENTA = cp.ID_CUENTA WHERE em.ID_EMPRESA = :idEmpresa AND p.ID_PRODUCTO = :idProducto ORDER BY p.NOMBRE ";
	public static final String UPDATE_ASOCIACION_EMPRESAS_PRODUCTOS = "UPDATE EMPRESAS_PRODUCTOS SET VALOR_MINIMO = :valorMinimo, VALOR_MAXIMO = :valorMaximo, VALOR_MAXIMO_DIA = :valorMaximoDia, HORA_INICIO_VENTA = :horaInicioVenta, HORA_FINAL_VENTA = :horaFinalVenta WHERE ID_EMPRESA = :idEmpresa AND ID_PRODUCTO = :idProducto";

	public static final String UPDATE_ASOCIACION_EMPRESAS_PRODUCTOS_COMISIONES = "UPDATE EMPRESAS_PRODUCTOS_COMISIONES SET PORCENTAJE_COMISION = :porcentajeComision, VALOR_FIJO_COMISION = :valorFijoComision WHERE ID_EMPRESA = :idEmpresa AND ID_PRODUCTO = :idProducto AND ID_COMISION = :idComision";

	public static final String UPDATE_ASOCIACION_CUENTAS_PRODUCTOS = "UPDATE CUENTAS_PRODUCTOS SET CUENTA_ASOCIADA = :cuentaAsociada WHERE ID_EMPRESA = :idEmpresa AND ID_PRODUCTO = :idProducto AND ID_CUENTA = :idCuenta";

}
